// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts"
  },
  datasource: {
    // `prisma migrate deploy` usa el motor propio de Prisma, no PrismaClientFactory.ts — necesita
    // su propio fix de TLS contra RDS Proxy. A diferencia de node-postgres, acá sslmode=require en
    // la URL sí funciona de forma confiable. Sin DEPLOY_ENV (migraciones locales) no se agrega SSL.
    url: `postgresql://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}/${process.env.DB_NAME}${
      process.env.DEPLOY_ENV && process.env.DEPLOY_ENV !== "local" ? "?sslmode=require" : ""
    }`,
  },
});
