import { UnitOfWork } from "@shared/database/UnitOfWork.js";
import { AggregateRoot } from "@shared/domain/entities/AggregateRoot.js";
import { DomainEvent } from "@shared/domain/entities/DomainEvent.js";
import { mock } from "vitest-mock-extended";
import { makeExecutionContextProvider } from "../../../support/executionContext.js";
import { OutboxRepository } from "@shared/domain/repositories/OutboxRepository.js";
import { OutboxPublisher } from "@shared/application/events/OutboxPublisher.js";
import { DomainEventDispatcher } from "@shared/application/orchestration/DomainEventDispatcher.js";
import { DomainEventHandler } from "@shared/application/events/DomainEventHandler.js";
import { Logger } from "@shared/logger/Logger.js";


function makeAggregateWithEvents(events: DomainEvent[]):AggregateRoot{
    return mock<AggregateRoot>({pullDomainEvents:()=>events});
}

describe("DomainEventDispatcher",()=>{

    function makeDeps(){
        const uow = mock<UnitOfWork>();
        uow.execute.mockImplementation(async (action) => action());
        const {executionContextProvider} = makeExecutionContextProvider();
        const outboxPublisher = mock<OutboxPublisher>();
        outboxPublisher.publish.mockResolvedValue(undefined);

        return {
            uow,
            outboxRepository: mock<OutboxRepository>(),
            outboxPublisher,
            executionContextProvider,
            logger: mock<Logger>()
        }
    }


    it("without events generated by the aggregate, it doesn't touch the outbox or publish", async ()=>{

        const deps = makeDeps();
        const dispatcher = new DomainEventDispatcher(deps.uow, deps.outboxRepository,deps.outboxPublisher,[],deps.executionContextProvider,deps.logger);
        
        await dispatcher.dispatcher(makeAggregateWithEvents([]), async()=>{});

        expect(deps.outboxRepository.create).not.toHaveBeenCalled();
        expect(deps.outboxPublisher.publish).not.toHaveBeenCalled();
   
    });


    it("with events, it persists them in the outbox and confirms (run handlers + publishes)", async ()=>{

        const deps = makeDeps();
        const fakeEvent = mock<DomainEvent>();
        const handler = mock<DomainEventHandler>();
        const dispatcher = new DomainEventDispatcher(deps.uow, deps.outboxRepository,deps.outboxPublisher,[handler],deps.executionContextProvider,deps.logger);
        
        await dispatcher.dispatcher(makeAggregateWithEvents([fakeEvent]), async()=>{});

        expect(deps.outboxRepository.create).toHaveBeenCalledOnce();
        expect(handler.handle).toHaveBeenCalledOnce();
        expect(deps.outboxPublisher.publish).toHaveBeenCalledOnce();
   
    });


    it("confirmFailure executes compensate, clears the outbox and runs the handlers as failed", async ()=>{

        const deps = makeDeps();
        const handler = mock<DomainEventHandler>();
        const compensate = vi.fn();
        const fakeEvent = mock<DomainEvent>();
        const dispatcher = new DomainEventDispatcher(deps.uow, deps.outboxRepository,deps.outboxPublisher,[handler],deps.executionContextProvider,deps.logger);
        
        await dispatcher.confirmFailure([fakeEvent],[],"external sync failed", compensate);

        expect(compensate).toHaveBeenCalledOnce();
        expect(deps.outboxRepository.delete).toHaveBeenCalledWith([],true);
        expect(handler.handle).toHaveBeenCalledWith(null,[fakeEvent],"FAILED","corr-1","external sync failed")
   
    });
    

});