version: 0.2

env:

  secrets-manager:
    DB_USER: "nova-oms/$DEPLOY_ENV/db:username"
    DB_PASSWORD: "nova-oms/$DEPLOY_ENV/db:password"
  parameter-store:
    DB_HOST:"/novaoms/$DEPLOY_ENV/db/host"
    DB_NAME:"/novaoms/$DEPLOY_ENV/db/name"

phases:
  install:
    runtime-versions:
      nodejs:24
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm exec prisma migrate deploy
      - pnpm exec tsx prisma/seed.ts